#ifndef __THP_REPLAY_TYPE_H__
#define __THP_REPLAY_TYPE_H__
/*
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MANUALLY MODIFY!!!
 */

#define ATTR_BYTE         (0x00 << 0)
#define ATTR_WORD         (0x01 << 0)
#define ATTR_DWORD        (0x02 << 0)
#define ATTR_QWORD        (0x03 << 0)
#define ATTR_UNSIGNED     (0x00 << 2)
#define ATTR_SIGNED       (0x01 << 2)
#define ATTR_DEC          (0x00 << 3)
#define ATTR_HEX          (0x01 << 3)
#define ATTR_CHAR         (0x02 << 3)
#define ATTR_BIN          (0x03 << 3)
#define ATTR_FLOAT        (0x04 << 3)
#define MAKE_ATTR(x)      ((x) << 24)

#define REPLAY_FILE_VERSION            44


//  group
#define GROUP_VERSION                  1                                                  // Version(sys,tsc,hal,fw,prj_id,tsa,etc)
#define GROUP_AFECAPS                  2                                                  // Afe caps info(tx_num,rx_num,etc)
#define GROUP_CONFIG                   3                                                  // Tsa config param
#define GROUP_INITIAL                  4                                                  // Initial Status(...)
#define GROUP_RUNNING                  5                                                  // Running Group
#define GROUP_CMD                      6                                                  // Command info
#define GROUP_FRAME                    7                                                  // Frame data
#define GROUP_DATA                     8                                                  // Data array(diff,ref,etc)
#define GROUP_VAR                      9                                                  // Variables(param,status,etc)
#define GROUP_REPORT                   10                                                 // Report info
#define GROUP_REQUEST                  11                                                 // Request info
#define GROUP_CALIBRATION              12                                                 // Panel or hardware calibration param
#define GROUP_TARGET                   13                                                 // Target output info
#define GROUP_ICINFO                   14                                                 // Ic info
#define GROUP_RECORD_ASSIST            15                                                 // Record assist info
#define GROUP_FRAME_ASSIST             16                                                 // Frame assist info
#define GROUP_DUMMY_GROUP              17                                                 // Maintain group continuity
#define GROUP_GOLDEN_TARGET            18                                                 // Golden target info
#define GROUP_SIMULATION_TARGET        19                                                 // Simulation target info
#define GROUP_STY_FRAME                20                                                 // Stylus frame data
#define GROUP_STY_PACKET               21                                                 // Stylus packet in frame data
#define GROUP_MAX                      21   


//  misc
#define MISC_GROUP_BEGIN               (0|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC))    // Index of group(version,afecaps,config,etc)
#define MISC_GROUP_END                 (1|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC))    // Index of group(version,afecaps,config,etc)
#define MISC_TEXT_LOG                  (2|MAKE_ATTR(ATTR_CHAR))                           // Any text log message(tsc,tsa,hal,etc)
#define MISC_REPLAY_HEAD               (3|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX))    // Replay log head content, only for tsc get replay log when save file
#define MISC_POINT_INDEX               (4|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC))    // Report point index
#define MISC_MAX                       5    

#define MISC_GROUP_BEGIN_SIZE          2    
#define MISC_GROUP_END_SIZE            2    
#define MISC_TEXT_LOG_SIZE             1    
#define MISC_REPLAY_HEAD_SIZE          1    
#define MISC_POINT_INDEX_SIZE          1    


//  version
#define VERSION_API_VER                (1000|MAKE_ATTR(ATTR_CHAR))                        // Version of tsa api
#define VERSION_TSA_VER                (1001|MAKE_ATTR(ATTR_CHAR))                        // Version of tsa algo
#define VERSION_TSA_KEY                (1002|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Secret key for tsa and fw (32 bytes)
#define VERSION_SYS_VER                (1003|MAKE_ATTR(ATTR_CHAR))                        // Version of machine and system
#define VERSION_TSC_VER                (1004|MAKE_ATTR(ATTR_CHAR))                        // Version of tsc
#define VERSION_HAL_VER                (1005|MAKE_ATTR(ATTR_CHAR))                        // Version of hal
#define VERSION_FW_VER                 (1006|MAKE_ATTR(ATTR_CHAR))                        // Version of fw
#define VERSION_PROJECT_ID             (1007|MAKE_ATTR(ATTR_CHAR))                        // ID of project
#define VERSION_APK_VER                (1008|MAKE_ATTR(ATTR_CHAR))                        // Version of gtptools (40 bytes)
#define VERSION_ROBOT_VER              (1009|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Version of robot (8 bytes)
#define VERSION_REP_FILE_VER           (1010|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_DEC)) // Version of replay file (4 bytes)
#define VERSION_STY_FRAME_VER          (1011|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Version of stylus framedata
#define VERSION_CHIP_UID_VER           (1012|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Version of chip uid (16 bytes)
#define VERSION_CUSTOMER_ID            (1013|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // customer id (1 byte)
#define VERSION_MAX                    13   

#define VERSION_API_VER_SIZE           1    
#define VERSION_TSA_VER_SIZE           1    
#define VERSION_TSA_KEY_SIZE           1    
#define VERSION_SYS_VER_SIZE           1    
#define VERSION_TSC_VER_SIZE           1    
#define VERSION_HAL_VER_SIZE           1    
#define VERSION_FW_VER_SIZE            1    
#define VERSION_PROJECT_ID_SIZE        1    
#define VERSION_APK_VER_SIZE           1    
#define VERSION_ROBOT_VER_SIZE         1    
#define VERSION_REP_FILE_VER_SIZE      4    
#define VERSION_STY_FRAME_VER_SIZE     1    
#define VERSION_CHIP_UID_VER_SIZE      1    


//  afecaps
#define AFECAPS_TX_NUM                 (2000|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Number of tx driver line
#define AFECAPS_RX_NUM                 (2001|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Number of rx sensor line
#define AFECAPS_BUTTON_NUM             (2002|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of button node
#define AFECAPS_FORCE_NUM              (2003|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of force node
#define AFECAPS_PITCH_SIZE             (2004|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Sensor pitch size in um
#define AFECAPS_SENSOR_ARCH            (2005|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Sensor architecture
#define AFECAPS_SENSOR_PATTERN         (2006|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Sensor pattern
#define AFECAPS_X_RESOLUTION           (2007|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Screen x resolution
#define AFECAPS_Y_RESOLUTION           (2008|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Screen y resolution
#define AFECAPS_X_REVERSAL             (2009|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // X coordinate reverse, 0:no reverse, !0:reverse
#define AFECAPS_Y_REVERSAL             (2010|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Y coordinate reverse, 0:no reverse, !0:reverse
#define AFECAPS_XY_SWAP                (2011|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // X to Y swap, 0:no swap, !0:swap
#define AFECAPS_SCAN_RATE_NUM          (2012|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of scan rate choices in active mode
#define AFECAPS_SCAN_RATE              (2013|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of all the scan rates
#define AFECAPS_MUTUAL_FREQ_NUM        (2014|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of mutual sample freq for hopping
#define AFECAPS_MUTUAL_FREQ            (2015|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of all the mutual sample freq
#define AFECAPS_SELF_TX_FREQ_NUM       (2016|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of self tx sample freq for hopping
#define AFECAPS_SELF_TX_FREQ           (2017|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of all the self tx sample freq
#define AFECAPS_SELF_RX_FREQ_NUM       (2018|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of self rx sample freq for hopping
#define AFECAPS_SELF_RX_FREQ           (2019|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of all the self rx sample freq
#define AFECAPS_STYLUS_FREQ_NUM        (2020|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of stylus sample freq for hopping
#define AFECAPS_STYLUS_FREQ            (2021|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of all the stylus sample freq
#define AFECAPS_NOISE_DURATION         (2022|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Duration of noise sample
#define AFECAPS_NOISE_FREQ_START       (2023|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Start freq of noise sample
#define AFECAPS_NOISE_FREQ_NUM         (2024|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Number of noise sample freq
#define AFECAPS_NOISE_FREQ             (2025|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of all the noise sample freq
#define AFECAPS_NOISE_DET_FEATURE      (2026|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_HEX)) // Afe noise detection feature
#define AFECAPS_FREQHOP_FEATURE        (2027|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_HEX)) // Afe freq hopping feature
#define AFECAPS_CALIB_FEATURE          (2028|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_HEX)) // Afe calibration feature
#define AFECAPS_GESTURE_FEATURE        (2029|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_HEX)) // Afe gesture feature
#define AFECAPS_STYLUS_FEATURE         (2030|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_HEX)) // Afe stylus feature
#define AFECAPS_DATA_TYPE              (2031|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_HEX)) // Afe data type(origin data or normalized data; rawdata or iqdata)
#define AFECAPS_MAX                    32   

#define AFECAPS_TX_NUM_SIZE            2    
#define AFECAPS_RX_NUM_SIZE            2    
#define AFECAPS_BUTTON_NUM_SIZE        1    
#define AFECAPS_FORCE_NUM_SIZE         1    
#define AFECAPS_PITCH_SIZE_SIZE        2    
#define AFECAPS_SENSOR_ARCH_SIZE       1    
#define AFECAPS_SENSOR_PATTERN_SIZE    1    
#define AFECAPS_X_RESOLUTION_SIZE      2    
#define AFECAPS_Y_RESOLUTION_SIZE      2    
#define AFECAPS_X_REVERSAL_SIZE        1    
#define AFECAPS_Y_REVERSAL_SIZE        1    
#define AFECAPS_XY_SWAP_SIZE           1    
#define AFECAPS_SCAN_RATE_NUM_SIZE     1    
#define AFECAPS_SCAN_RATE_SIZE         2    
#define AFECAPS_MUTUAL_FREQ_NUM_SIZE   1    
#define AFECAPS_MUTUAL_FREQ_SIZE       2    
#define AFECAPS_SELF_TX_FREQ_NUM_SIZE  1    
#define AFECAPS_SELF_TX_FREQ_SIZE      2    
#define AFECAPS_SELF_RX_FREQ_NUM_SIZE  1    
#define AFECAPS_SELF_RX_FREQ_SIZE      2    
#define AFECAPS_STYLUS_FREQ_NUM_SIZE   1    
#define AFECAPS_STYLUS_FREQ_SIZE       2    
#define AFECAPS_NOISE_DURATION_SIZE    2    
#define AFECAPS_NOISE_FREQ_START_SIZE  2    
#define AFECAPS_NOISE_FREQ_NUM_SIZE    2    
#define AFECAPS_NOISE_FREQ_SIZE        2    
#define AFECAPS_NOISE_DET_FEATURE_SIZE 2    
#define AFECAPS_FREQHOP_FEATURE_SIZE   2    
#define AFECAPS_CALIB_FEATURE_SIZE     2    
#define AFECAPS_GESTURE_FEATURE_SIZE   2    
#define AFECAPS_STYLUS_FEATURE_SIZE    2    
#define AFECAPS_DATA_TYPE_SIZE         2    


//  config
#define CONFIG_TSA_PARAM               (3000|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Parameter struct of tsa configuration
#define CONFIG_TSA_PARAM_VERSION       (3001|MAKE_ATTR(ATTR_CHAR))                        // Parameter version of tsa configuration
#define CONFIG_FW_PARAM                (3002|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Parameter struct of fw configuration
#define CONFIG_MAX                     3    

#define CONFIG_TSA_PARAM_SIZE          1    
#define CONFIG_TSA_PARAM_VERSION_SIZE  1    
#define CONFIG_FW_PARAM_SIZE           1    


//  initial
#define INITIAL_INITIAL_FLEX_DATA      (4000|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Only for data record, the length of this dynamic structure is not stable
#define INITIAL_INITIAL_MUTUAL_REF     (4001|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of inital mutual ref, data format:[tx][rx]
#define INITIAL_INITIAL_SELF_REF       (4002|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of inital self ref, data format:[tx+rx],tx first
#define INITIAL_INITIAL_NOCLEAN_VAR    (4003|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Array of inital noclean data
#define INITIAL_INITIAL_FLASH_DATA     (4004|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Array of inital KB matrix data
#define INITIAL_NOCLEAN_SOURCE_DATA    (4100|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Array of original noclean data, before decoding
#define INITIAL_REF_SOURCE_DATA        (4101|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of original ref, include self and mutual
#define INITIAL_MAX                    7    

#define INITIAL_INITIAL_FLEX_DATA_SIZE 1    
#define INITIAL_INITIAL_MUTUAL_REF_SIZE 2    
#define INITIAL_INITIAL_SELF_REF_SIZE  2    
#define INITIAL_INITIAL_NOCLEAN_VAR_SIZE 1    
#define INITIAL_INITIAL_FLASH_DATA_SIZE 1    
#define INITIAL_NOCLEAN_SOURCE_DATA_SIZE 1    
#define INITIAL_REF_SOURCE_DATA_SIZE   2    


//  cmd
#define CMD_TSA_CMD                    (5000|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Array of Command and command data
#define CMD_MAX                        1    

#define CMD_TSA_CMD_SIZE               1    


//  frame
#define FRAME_PROC_TIME_STAMP          (6000|MAKE_ATTR(ATTR_QWORD|ATTR_UNSIGNED|ATTR_DEC)) // Process time stamp, record by AfeHal, in us units
#define FRAME_SAMPLE_TIME_STAMP        (6001|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Sample time stamp, record by TPIC, in ms units
#define FRAME_FRAME_INDEX              (6002|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Framedata index, count by TPIC
#define FRAME_SCAN_RATE                (6003|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Current scan rate, unit in Hz
#define FRAME_STATUS                   (6004|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Status of afe
#define FRAME_REQUEST                  (6005|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Request of afe
#define FRAME_GESTURE                  (6006|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Gesture of afe
#define FRAME_MUTUAL_DURATION          (6007|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Duration of mutual sample
#define FRAME_MUTUAL_FREQ_A            (6008|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Frequence A of mutual sample
#define FRAME_MUTUAL_FREQ_B            (6009|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Frequence B of mutual sample
#define FRAME_MUTUAL_DATA              (6010|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of mutual rawdata, data format:[tx][rx]
#define FRAME_SELF_TX_DURATION         (6011|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Duration of self tx sample
#define FRAME_SELF_RX_DURATION         (6012|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Duration of self rx sample
#define FRAME_SELF_TX_FREQ             (6013|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Frequence of self tx sample
#define FRAME_SELF_RX_FREQ             (6014|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Frequence of self rx sample
#define FRAME_SELF_DATA                (6015|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of self rawdata, data format:[tx+rx],tx first
#define FRAME_NOISE_DATA               (6016|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of noise rawdata
#define FRAME_HOVER_DATA               (6017|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of hover rawdata
#define FRAME_IM_DATA                  (6018|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of im rawdata
#define FRAME_IQ_DATA                  (6019|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of iq rawdata
#define FRAME_BUTTON_DATA              (6020|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of button rawdata
#define FRAME_FORCE_DATA               (6021|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of force rawdata
#define FRAME_NOISE_TYPE               (6022|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Noise type of current sample that distinguish by firmware
#define FRAME_STYLUS_DATA              (6023|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of stylus rawdata
#define FRAME_STYLUS_DATA2             (6024|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of stylus rawdata2
#define FRAME_MUTUAL_ADC               (6025|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of mutual adc data
#define FRAME_SELF_ADC                 (6026|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of self adc data
#define FRAME_NOISE_ADC                (6027|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of noise adc data
#define FRAME_TICK_100MS               (6028|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Tick 100ms of fw when fw_record_mode is 1:sync_low_speed
#define FRAME_FRAME_STATUS             (6029|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Skip status(bit0:ByLcdNoise/bit1:ByBuildRef/bit2:ByHopping/bit3-7:res)
#define FRAME_FRAME_LOG                (6030|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Array of frame log
#define FRAME_FW_MODE                  (6031|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Fw status(bit0-1:res/bit2:LowTempMode/bit3:WaterMode/bit4:BArrayStudyMode/bit5:GameMode/bit6:HighRateMode/bit7:ChargeMode)
#define FRAME_NOISE_STATE              (6032|MAKE_ATTR(ATTR_QWORD|ATTR_UNSIGNED|ATTR_HEX)) // Noise status(byte0:NoiseGrade/byte1:NoiseFlag/byte2-3:NoiseType/byte4-5:ImFilter/byte6:NoiseLevel/byte7:res)
#define FRAME_IM_ADC                   (6033|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of im adc data
#define FRAME_MAX_COM_NOISE            (6034|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of max common noise
#define FRAME_MAX_LCD_NOISE            (6035|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of max lcd noise
#define FRAME_MUTUAL_FREQ_A_IDX        (6036|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Index of frequence a
#define FRAME_ATTR_BUF                 (6037|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Array of attribute buffer
#define FRAME_FREQ_CONSST_ORG          (6038|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of all frequencies consistency before normalize
#define FRAME_FREQ_CONSST              (6039|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of all frequencies consistency
#define FRAME_TEMPRATURE               (6040|MAKE_ATTR(ATTR_BYTE|ATTR_SIGNED|ATTR_DEC))   // Array of temperature and confidence
#define FRAME_I_DATA                   (6041|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // Array of i rawdata
#define FRAME_Q_DATA                   (6042|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // Array of q rawdata
#define FRAME_CROSS_RAWDATA            (6043|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of cross rawdata
#define FRAME_EVENT                    (6044|MAKE_ATTR(ATTR_QWORD|ATTR_UNSIGNED|ATTR_HEX)) // Current event data
#define FRAME_PACK_EN                  (6045|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Pack enable flags
#define FRAME_TYPE_EN                  (6046|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Type enable flags
#define FRAME_FRAME_INFO               (6047|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Array of frame info
#define FRAME_TICK_256US               (6048|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // The high 8 bits of the RTC clock, with each bit representing 256 us
#define FRAME_FRAME_SOURCE_DATA        (6100|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Array of original framedata, before decoding
#define FRAME_MAX                      50   

#define FRAME_PROC_TIME_STAMP_SIZE     8    
#define FRAME_SAMPLE_TIME_STAMP_SIZE   2    
#define FRAME_FRAME_INDEX_SIZE         2    
#define FRAME_SCAN_RATE_SIZE           2    
#define FRAME_STATUS_SIZE              4    
#define FRAME_REQUEST_SIZE             4    
#define FRAME_GESTURE_SIZE             4    
#define FRAME_MUTUAL_DURATION_SIZE     2    
#define FRAME_MUTUAL_FREQ_A_SIZE       2    
#define FRAME_MUTUAL_FREQ_B_SIZE       2    
#define FRAME_MUTUAL_DATA_SIZE         2    
#define FRAME_SELF_TX_DURATION_SIZE    2    
#define FRAME_SELF_RX_DURATION_SIZE    2    
#define FRAME_SELF_TX_FREQ_SIZE        2    
#define FRAME_SELF_RX_FREQ_SIZE        2    
#define FRAME_SELF_DATA_SIZE           2    
#define FRAME_NOISE_DATA_SIZE          2    
#define FRAME_HOVER_DATA_SIZE          2    
#define FRAME_IM_DATA_SIZE             2    
#define FRAME_IQ_DATA_SIZE             2    
#define FRAME_BUTTON_DATA_SIZE         2    
#define FRAME_FORCE_DATA_SIZE          2    
#define FRAME_NOISE_TYPE_SIZE          4    
#define FRAME_STYLUS_DATA_SIZE         2    
#define FRAME_STYLUS_DATA2_SIZE        2    
#define FRAME_MUTUAL_ADC_SIZE          2    
#define FRAME_SELF_ADC_SIZE            2    
#define FRAME_NOISE_ADC_SIZE           2    
#define FRAME_TICK_100MS_SIZE          1    
#define FRAME_FRAME_STATUS_SIZE        1    
#define FRAME_FRAME_LOG_SIZE           1    
#define FRAME_FW_MODE_SIZE             1    
#define FRAME_NOISE_STATE_SIZE         8    
#define FRAME_IM_ADC_SIZE              2    
#define FRAME_MAX_COM_NOISE_SIZE       2    
#define FRAME_MAX_LCD_NOISE_SIZE       2    
#define FRAME_MUTUAL_FREQ_A_IDX_SIZE   1    
#define FRAME_ATTR_BUF_SIZE            1    
#define FRAME_FREQ_CONSST_ORG_SIZE     2    
#define FRAME_FREQ_CONSST_SIZE         2    
#define FRAME_TEMPRATURE_SIZE          1    
#define FRAME_I_DATA_SIZE              2    
#define FRAME_Q_DATA_SIZE              2    
#define FRAME_CROSS_RAWDATA_SIZE       2    
#define FRAME_EVENT_SIZE               8    
#define FRAME_PACK_EN_SIZE             1    
#define FRAME_TYPE_EN_SIZE             4    
#define FRAME_FRAME_INFO_SIZE          1    
#define FRAME_TICK_256US_SIZE          1    
#define FRAME_FRAME_SOURCE_DATA_SIZE   1    


//  data
#define DATA_DEBUG_FLEX_DATA           (7000|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Only for data record, the length of this dynamic structure is not stable
#define DATA_MUTUAL_DIFF               (7001|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // Array of mutual diffdata, data format:[tx][rx]
#define DATA_SELF_DIFF                 (7002|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // Array of self diffdata, data format:[tx+rx],tx first
#define DATA_MUTUAL_REF                (7003|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of mutual refdata, data format:[tx][rx]
#define DATA_SELF_REF                  (7004|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of self refdata, data format:[tx+rx],tx first
#define DATA_VIVO_DEBUG                (7005|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of vivo debug info
#define DATA_COORD_INFO                (7006|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of no fw smooth coord info for vivo
#define DATA_NORMALIZE_K               (7007|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of normalize K for all frequencies
#define DATA_NORMALIZE_B               (7008|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of normalize B for all frequencies
#define DATA_REF_UP_TYPE               (7009|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Type of ref update
#define DATA_MAX                       10   

#define DATA_DEBUG_FLEX_DATA_SIZE      1    
#define DATA_MUTUAL_DIFF_SIZE          2    
#define DATA_SELF_DIFF_SIZE            2    
#define DATA_MUTUAL_REF_SIZE           2    
#define DATA_SELF_REF_SIZE             2    
#define DATA_VIVO_DEBUG_SIZE           2    
#define DATA_COORD_INFO_SIZE           2    
#define DATA_NORMALIZE_K_SIZE          2    
#define DATA_NORMALIZE_B_SIZE          2    
#define DATA_REF_UP_TYPE_SIZE          2    


//  var
#define VAR_MAX                        0    



//  report
#define REPORT_TIME_STAMP              (9000|MAKE_ATTR(ATTR_QWORD|ATTR_UNSIGNED|ATTR_DEC)) // Report time stamp, record by tsa
#define REPORT_TOUCH_NUM               (9001|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of detected touch
#define REPORT_TRACKING_ID             (9002|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Track ID of a certain touch
#define REPORT_TYPE                    (9003|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Type of a certain touch (finger/stylus)
#define REPORT_X_POS                   (9004|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Position x of a certain touch, units according to x_resolution
#define REPORT_Y_POS                   (9005|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Position y of a certain touch, units according to y_resolution
#define REPORT_PRESSURE                (9006|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Pressure of a certain touch, in arbitrary units
#define REPORT_DISTANCE                (9007|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Distance between panel and object, in arbitrary units, Zero means touch the panel
#define REPORT_TOUCH_MAJOR             (9008|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // The length of the major axis of the touch ellipse
#define REPORT_TOUCH_MINOR             (9009|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // The length of the minor axis of the touch ellipse
#define REPORT_ORIENTATION             (9010|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // The orientation of the touch ellipse, -90°~90°
#define REPORT_COVER_FP                (9011|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Finger print cover status
#define REPORT_IS_FULL_HOVER           (9012|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Full hover status
#define REPORT_IS_LARGE_TOUCH          (9013|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Large touch status
#define REPORT_ERROR_FLAG              (9014|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Report error flag
#define REPORT_MASK_FLAG               (9015|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Artificially Mask flag for rep data,  exp. volume_key + power_key to record issue data
#define REPORT_STYLUS_STATUS           (9016|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Depend on distance. if distance>0, val = 3; others, val = 4 (3:hover; 4:Tip)
#define REPORT_IS_CANCEL_TOUCH         (9017|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Cacel touch status, every point x/y need equip it
#define REPORT_X_TILT                  (9018|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // tilt of x direction, -90°~90°
#define REPORT_Y_TILT                  (9019|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // tilt of y direction, -90°~90°
#define REPORT_REF_NOT_SET             (9020|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Ref not set flag
#define REPORT_ID_CANCEL_FLAG          (9021|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // cancel flag of tracking id
#define REPORT_STYLUS_KEY              (9022|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC))
#define REPORT_MAX                     20   

#define REPORT_TIME_STAMP_SIZE         8    
#define REPORT_TOUCH_NUM_SIZE          1    
#define REPORT_TRACKING_ID_SIZE        1    
#define REPORT_TYPE_SIZE               1    
#define REPORT_X_POS_SIZE              2    
#define REPORT_Y_POS_SIZE              2    
#define REPORT_PRESSURE_SIZE           2    
#define REPORT_DISTANCE_SIZE           2    
#define REPORT_TOUCH_MAJOR_SIZE        2    
#define REPORT_TOUCH_MINOR_SIZE        2    
#define REPORT_ORIENTATION_SIZE        2    
#define REPORT_COVER_FP_SIZE           1    
#define REPORT_IS_FULL_HOVER_SIZE      1    
#define REPORT_IS_LARGE_TOUCH_SIZE     1    
#define REPORT_ERROR_FLAG_SIZE         1    
#define REPORT_MASK_FLAG_SIZE          2    
#define REPORT_STYLUS_STATUS_SIZE      1    
#define REPORT_IS_CANCEL_TOUCH_SIZE    1    
#define REPORT_X_TILT_SIZE             2    
#define REPORT_Y_TILT_SIZE             2    


//  request
#define REQUEST_TSA_REQUEST            (10010|MAKE_ATTR(ATTR_QWORD|ATTR_UNSIGNED|ATTR_DEC)) // Command(uint32_t) and command data(uint32_t)
#define REQUEST_MAX                    1    

#define REQUEST_TSA_REQUEST_SIZE       8    


//  calibration
#define CALIBRATION_MUTUAL_CALIB_INDEX (3500|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Index of mutual calibration matrix
#define CALIBRATION_MUTUAL_FREQ_A      (3501|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Mutual freq a by index
#define CALIBRATION_MUTUAL_FREQ_B      (3502|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Mutual freq b by index
#define CALIBRATION_MUTUAL_K           (3503|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Mutual calibration K coef by index, base 4096
#define CALIBRATION_MUTUAL_B           (3504|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // Mutual calibration B coef by index
#define CALIBRATION_SELF_CALIB_INDEX   (3505|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Index of self calibration matrix
#define CALIBRATION_SELF_TX_FREQ       (3506|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Self tx freq by index
#define CALIBRATION_SELF_RX_FREQ       (3507|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Self rx freq by index
#define CALIBRATION_SELF_K             (3508|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Self calibration K coef by index, base 4096
#define CALIBRATION_SELF_B             (3509|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // Self calibration B coef by index
#define CALIBRATION_FW_MUTUAL_CALIB_INDEX (3510|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Index of firmware mutual calibration matrix
#define CALIBRATION_FW_MUTUAL_FREQ_A   (3511|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Firmware mutual freq a by index
#define CALIBRATION_FW_MUTUAL_FREQ_B   (3512|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Firmware mutual freq b by index
#define CALIBRATION_FW_MUTUAL_K_MATRIX (3513|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Firmware mutual calibration K coef matrix by index, base 4096 (K is matrix)
#define CALIBRATION_FW_MUTUAL_K_VALUE  (3514|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Firmware mutual calibration K coef value by index, base 128 (K is value)
#define CALIBRATION_FW_MUTUAL_B_MATRIX (3515|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // Firmware mutual calibration B coef matrix by index
#define CALIBRATION_FW_SELF_CALIB_INDEX (3516|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Index of firmware self calibration matrix
#define CALIBRATION_FW_SELF_TX_FREQ    (3517|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Firmware self tx freq by index
#define CALIBRATION_FW_SELF_RX_FREQ    (3518|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Firmware self rx freq by index
#define CALIBRATION_FW_SELF_K_MATRIX   (3519|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Firmware self calibration K coef matrix by index, base 4096 (K is matrix)
#define CALIBRATION_FW_SELF_K_VALUE    (3520|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Firmware self calibration K coef value by index, base 128(K is value)
#define CALIBRATION_FW_SELF_B_MATRIX   (3521|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))   // Firmware self calibration B coef matrix by index
#define CALIBRATION_MAX                22   

#define CALIBRATION_MUTUAL_CALIB_INDEX_SIZE 1    
#define CALIBRATION_MUTUAL_FREQ_A_SIZE 2    
#define CALIBRATION_MUTUAL_FREQ_B_SIZE 2    
#define CALIBRATION_MUTUAL_K_SIZE      2    
#define CALIBRATION_MUTUAL_B_SIZE      2    
#define CALIBRATION_SELF_CALIB_INDEX_SIZE 1    
#define CALIBRATION_SELF_TX_FREQ_SIZE  2    
#define CALIBRATION_SELF_RX_FREQ_SIZE  2    
#define CALIBRATION_SELF_K_SIZE        2    
#define CALIBRATION_SELF_B_SIZE        2    
#define CALIBRATION_FW_MUTUAL_CALIB_INDEX_SIZE 1    
#define CALIBRATION_FW_MUTUAL_FREQ_A_SIZE 2    
#define CALIBRATION_FW_MUTUAL_FREQ_B_SIZE 2    
#define CALIBRATION_FW_MUTUAL_K_MATRIX_SIZE 2    
#define CALIBRATION_FW_MUTUAL_K_VALUE_SIZE 2    
#define CALIBRATION_FW_MUTUAL_B_MATRIX_SIZE 2    
#define CALIBRATION_FW_SELF_CALIB_INDEX_SIZE 1    
#define CALIBRATION_FW_SELF_TX_FREQ_SIZE 2    
#define CALIBRATION_FW_SELF_RX_FREQ_SIZE 2    
#define CALIBRATION_FW_SELF_K_MATRIX_SIZE 2    
#define CALIBRATION_FW_SELF_K_VALUE_SIZE 2    
#define CALIBRATION_FW_SELF_B_MATRIX_SIZE 2    


//  target
#define TARGET_CASE_TYPE               (11000|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Type of test case(objective_test/experience_test)
#define TARGET_TOUCH_TYPE              (11001|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Type of touch(finger/stylus/finger-stylus)
#define TARGET_MAIN_SCENARIO           (11002|MAKE_ATTR(ATTR_QWORD|ATTR_UNSIGNED|ATTR_HEX)) // Main scenario, each bit represents a different scene
#define TARGET_SUB_SCENARIO            (11003|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Sub scenario, each bit represents a different scene
#define TARGET_TOUCH_OBJECT            (11004|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Object, each bit represents a different object
#define TARGET_TOUCH_OPERATION         (11005|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Operation, each bit represents a different operation
#define TARGET_TOUCH_SPEED             (11006|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Speed, each bit represents a different operation
#define TARGET_TOUCH_REL_POS           (11007|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Relative position, each bit represents a different rel-pos
#define TARGET_TOUCH_DISTANCE          (11008|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Distance, each bit represents a different distance
#define TARGET_FRAME_INDEX             (11009|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Framedata index
#define TARGET_TOUCH_NUM               (11010|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of detected touch
#define TARGET_TRACKING_ID             (11011|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Track ID of a certain touch
#define TARGET_TYPE                    (11012|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Type of a certain touch (finger/stylus)
#define TARGET_X_POS                   (11013|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Position x of a certain touch, units according to x_resolution
#define TARGET_Y_POS                   (11014|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Position y of a certain touch, units according to y_resolution
#define TARGET_PRESSURE                (11015|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Pressure of a certain touch, in arbitrary units
#define TARGET_DISTANCE                (11016|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Distance between panel and object, in arbitrary units, Zero means touch the panel
#define TARGET_TOUCH_MAJOR             (11017|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // The length of the major axis of the touch ellipse
#define TARGET_TOUCH_MINOR             (11018|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // The length of the minor axis of the touch ellipse
#define TARGET_ORIENTATION             (11019|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // The orientation of the touch ellipse, -90°~90°
#define TARGET_COVER_FP                (11020|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Finger print cover status
#define TARGET_IS_FULL_HOVER           (11021|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Full hover status
#define TARGET_IS_LARGE_TOUCH          (11022|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Large touch status
#define TARGET_TIME_STAMP              (11023|MAKE_ATTR(ATTR_QWORD|ATTR_UNSIGNED|ATTR_DEC)) // Sample target value time stamp, record by robot/apk/tsa
#define TARGET_TARGET_TYPE             (11024|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Type of current target(bit0:fw/bit1:fw_with_tpl/bit2:template/bit3:robot)
#define TARGET_TEMPLATE_STAGE          (11025|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stage of template record(0:null/1:notouch/2:fuzzy/3:truth)
#define TARGET_CUR_TPL_ROUND           (11026|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Round index of current frame in template mode(0:null/other:round index)
#define TARGET_STYLUS_STATUS           (11027|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Type of stylus status (1:finger;2:outrange;3:hover;4:Tip)
#define TARGET_X_STYLUS_ANGLE          (11028|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Angle of stylus x of stylus,-90°~90°
#define TARGET_Y_STYLUS_ANGLE          (11029|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Angle of stylus y of stylus,-90°~90°
#define TARGET_STYLUS_POS_INDEX        (11030|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // stylus pos index in stylus mode
#define TARGET_TARGET_SOURCE_DATA      (11100|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Array of original target data, before decoding
#define TARGET_MAX                     32   

#define TARGET_CASE_TYPE_SIZE          1    
#define TARGET_TOUCH_TYPE_SIZE         1    
#define TARGET_MAIN_SCENARIO_SIZE      8    
#define TARGET_SUB_SCENARIO_SIZE       4    
#define TARGET_TOUCH_OBJECT_SIZE       4    
#define TARGET_TOUCH_OPERATION_SIZE    4    
#define TARGET_TOUCH_SPEED_SIZE        4    
#define TARGET_TOUCH_REL_POS_SIZE      4    
#define TARGET_TOUCH_DISTANCE_SIZE     4    
#define TARGET_FRAME_INDEX_SIZE        2    
#define TARGET_TOUCH_NUM_SIZE          1    
#define TARGET_TRACKING_ID_SIZE        1    
#define TARGET_TYPE_SIZE               1    
#define TARGET_X_POS_SIZE              2    
#define TARGET_Y_POS_SIZE              2    
#define TARGET_PRESSURE_SIZE           2    
#define TARGET_DISTANCE_SIZE           2    
#define TARGET_TOUCH_MAJOR_SIZE        2    
#define TARGET_TOUCH_MINOR_SIZE        2    
#define TARGET_ORIENTATION_SIZE        2    
#define TARGET_COVER_FP_SIZE           1    
#define TARGET_IS_FULL_HOVER_SIZE      1    
#define TARGET_IS_LARGE_TOUCH_SIZE     1    
#define TARGET_TIME_STAMP_SIZE         8    
#define TARGET_TARGET_TYPE_SIZE        2    
#define TARGET_TEMPLATE_STAGE_SIZE     1    
#define TARGET_CUR_TPL_ROUND_SIZE      2    
#define TARGET_STYLUS_STATUS_SIZE      1    
#define TARGET_X_STYLUS_ANGLE_SIZE     2    
#define TARGET_Y_STYLUS_ANGLE_SIZE     2    
#define TARGET_STYLUS_POS_INDEX_SIZE   1    
#define TARGET_TARGET_SOURCE_DATA_SIZE 1    


//  icinfo
#define ICINFO_IC_INFO_DATA            (12000|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Record the ic info, the length of this dynamic structure is not stable
#define ICINFO_MAX                     1    

#define ICINFO_IC_INFO_DATA_SIZE       1    


//  record_assist
#define RECORD_ASSIST_FW_RECORD_MODE   (13000|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Fw mode when record data(0:null/1:wait_low_speed/2:no_wait_high_speed)
#define RECORD_ASSIST_TARGET_TYPE      (13001|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // All type of target in this data(bit0:fw/bit1:fw_with_tpl/bit2:template/bit3:robot)
#define RECORD_ASSIST_TARGET_INFO      (13002|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_DEC)) // All kind of target info in this data(bit0:coord/bit1:large/bit2:fp/bit3:hover)
#define RECORD_ASSIST_INIT_VELOCITY    (13003|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Initial velocity of slide in the template/robot mode, unit mm/s^2, for all finger same velocity
#define RECORD_ASSIST_ACCELERATION     (13004|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Acceleration of slide in the template/robot mode(other:acceleration no-change/0xffff:mutil-acceleration), unit mm/s, for all finger same Acceleration
#define RECORD_ASSIST_SOFT_INIT        (13005|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Execute soft init or not before record data(0:null/1:enable)
#define RECORD_ASSIST_MAX_DEVIATION    (13006|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Max deviation between fw-template target in the template mode, unit mm
#define RECORD_ASSIST_TPL_ROUND_TOTAL  (13007|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Total rounds in the template mode(0:null/other:total rounds num)
#define RECORD_ASSIST_RECORD_STYLUS    (13008|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus framedata mode(0:null/1:stylus_low_speed/2:stylus_high_speed)
#define RECORD_ASSIST_MAX              9    

#define RECORD_ASSIST_FW_RECORD_MODE_SIZE 1    
#define RECORD_ASSIST_TARGET_TYPE_SIZE 2    
#define RECORD_ASSIST_TARGET_INFO_SIZE 4    
#define RECORD_ASSIST_INIT_VELOCITY_SIZE 2    
#define RECORD_ASSIST_ACCELERATION_SIZE 2    
#define RECORD_ASSIST_SOFT_INIT_SIZE   1    
#define RECORD_ASSIST_MAX_DEVIATION_SIZE 2    
#define RECORD_ASSIST_TPL_ROUND_TOTAL_SIZE 2    
#define RECORD_ASSIST_RECORD_STYLUS_SIZE 1    


//  frame_assist
#define FRAME_ASSIST_DISTANCE          (14000|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Distance between panel and object in the robot mode, in arbitrary units, Zero means touch the panel
#define FRAME_ASSIST_TEMPLATE_STAGE    (14001|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stage of template record in the template mode(0:null/1:notouch/2:fuzzy/3:truth)
#define FRAME_ASSIST_VELOCITY          (14002|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Velocity of slide in the template/robot mode, unit mm/s, for all finger same velocity
#define FRAME_ASSIST_CUR_TPL_ROUND     (14003|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Round index of current frame in template mode(0:null/other:round index)
#define FRAME_ASSIST_MAX               4    

#define FRAME_ASSIST_DISTANCE_SIZE     2    
#define FRAME_ASSIST_TEMPLATE_STAGE_SIZE 1    
#define FRAME_ASSIST_VELOCITY_SIZE     2    
#define FRAME_ASSIST_CUR_TPL_ROUND_SIZE 2    


//  golden_target
#define GOLDEN_TARGET_FRAME_INDEX      (15000|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_DEC)) // Frame number in sequence, starting from 0
#define GOLDEN_TARGET_FINGER_NUMBER    (15001|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Finger number, express the truth-valued range in the form of a closed interval
#define GOLDEN_TARGET_I_X_Y_W          (15002|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // i: track ID, x, y: coordinates, w: weight, length = finger number * 4 * sizeof(u16)
#define GOLDEN_TARGET_LARGE_STATE      (15003|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stage of large touch
#define GOLDEN_TARGET_WATER_STATE      (15004|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stage of water mode
#define GOLDEN_TARGET_RECT_INFO        (15005|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Info of rect, top/bottom/left/right, length = finger_number * sizeof(u32)
#define GOLDEN_TARGET_I_X_Y_W_ORI      (15006|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // i: track ID, x, y: coordinates, w: weight, length = finger number * 4 * sizeof(u16)
#define GOLDEN_TARGET_STABLE_POINT     (15007|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of structures for stable_point, i_x_y, i: track ID, x, y: coordinates
#define GOLDEN_TARGET_RECT_DIFF_MAX    (15008|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of rect diff max, the same indexes as array rect_info
#define GOLDEN_TARGET_STY_COORD_STATE  (15009|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stage of stylus coordinate, 1:finger;2:outrange;3:hover;4:tip
#define GOLDEN_TARGET_STY_POS_INDEX    (15010|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus pos index
#define GOLDEN_TARGET_DIAMETER         (15900|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // The diameter of the single copper pillar, unit 0.1mm
#define GOLDEN_TARGET_MAX              12   

#define GOLDEN_TARGET_FRAME_INDEX_SIZE 4    
#define GOLDEN_TARGET_FINGER_NUMBER_SIZE 1    
#define GOLDEN_TARGET_I_X_Y_W_SIZE     2    
#define GOLDEN_TARGET_LARGE_STATE_SIZE 1    
#define GOLDEN_TARGET_WATER_STATE_SIZE 1    
#define GOLDEN_TARGET_RECT_INFO_SIZE   4    
#define GOLDEN_TARGET_I_X_Y_W_ORI_SIZE 2    
#define GOLDEN_TARGET_STABLE_POINT_SIZE 2    
#define GOLDEN_TARGET_RECT_DIFF_MAX_SIZE 2    
#define GOLDEN_TARGET_STY_COORD_STATE_SIZE 1    
#define GOLDEN_TARGET_STY_POS_INDEX_SIZE 1    
#define GOLDEN_TARGET_DIAMETER_SIZE    2    


//  simulation_target
#define SIMULATION_TARGET_FRAME_INDEX  (16000|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_DEC)) // Frame number in sequence, starting from 0
#define SIMULATION_TARGET_FINGER_NUMBER (16001|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Finger number, actually report points
#define SIMULATION_TARGET_I_X_Y_W      (16002|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // i: track ID, x, y: coordinates, w: weight, length = finger number * 4 * sizeof(u16)
#define SIMULATION_TARGET_I_X_Y_W_ORI  (16003|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // i: track ID, x, y: coordinates, w: weight, length = finger number * 4 * sizeof(u16)
#define SIMULATION_TARGET_MUTUAL_RAW   (16100|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of mutual rawdata
#define SIMULATION_TARGET_MUTUAL_DIFF  (16101|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of mutual diffdata
#define SIMULATION_TARGET_MUTUAL_REF   (16102|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of mutual refdata
#define SIMULATION_TARGET_SELF_RAW     (16103|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of self rawdata
#define SIMULATION_TARGET_SELF_DIFF    (16104|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of self diffdata
#define SIMULATION_TARGET_SEF_REF      (16105|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of self refdata
#define SIMULATION_TARGET_RECTANGE_NUMBER (16110|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Number of rectange after region search
#define SIMULATION_TARGET_TOP_SIGN     (16111|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Info of top sign, length = tx * rx * sizeof(u8)
#define SIMULATION_TARGET_RECT_INFO    (16112|MAKE_ATTR(ATTR_DWORD|ATTR_UNSIGNED|ATTR_HEX)) // Info of rect, top/bottom/left/right, length = rectange number * sizeof(u32)
#define SIMULATION_TARGET_RECT_DIFF_MAX (16113|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of rect diff max, the same indexes as array rect_info
#define SIMULATION_TARGET_TOUCH_LEVEL  (16114|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // TouchLevel obtained from the configuration file
#define SIMULATION_TARGET_LEAVE_LEVEL  (16115|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // LeaveLevel obtained from the configuration file
#define SIMULATION_TARGET_LARGE_STATE  (16120|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stage of large touch
#define SIMULATION_TARGET_WATER_STATE  (16121|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stage of water mode
#define SIMULATION_TARGET_STY_ENTER_FLAG (16150|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Judgment of entering stylus mode
#define SIMULATION_TARGET_STY_POS_INDEX (16151|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus pos index
#define SIMULATION_TARGET_STY_COORD_STATE (16152|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stage of stylus coordinate, 1:finger;2:outrange;3:hover;4:tip
#define SIMULATION_TARGET_X_STYLUS_ANGLE (16153|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Angle of stylus x of stylus,-90°~90°
#define SIMULATION_TARGET_Y_STYLUS_ANGLE (16154|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Angle of stylus y of stylus,-90°~90°
#define SIMULATION_TARGET_MAX          23   

#define SIMULATION_TARGET_FRAME_INDEX_SIZE 4    
#define SIMULATION_TARGET_FINGER_NUMBER_SIZE 1    
#define SIMULATION_TARGET_I_X_Y_W_SIZE 2    
#define SIMULATION_TARGET_I_X_Y_W_ORI_SIZE 2    
#define SIMULATION_TARGET_MUTUAL_RAW_SIZE 2    
#define SIMULATION_TARGET_MUTUAL_DIFF_SIZE 2    
#define SIMULATION_TARGET_MUTUAL_REF_SIZE 2    
#define SIMULATION_TARGET_SELF_RAW_SIZE 2    
#define SIMULATION_TARGET_SELF_DIFF_SIZE 2    
#define SIMULATION_TARGET_SEF_REF_SIZE 2    
#define SIMULATION_TARGET_RECTANGE_NUMBER_SIZE 1    
#define SIMULATION_TARGET_TOP_SIGN_SIZE 1    
#define SIMULATION_TARGET_RECT_INFO_SIZE 4    
#define SIMULATION_TARGET_RECT_DIFF_MAX_SIZE 2    
#define SIMULATION_TARGET_TOUCH_LEVEL_SIZE 2    
#define SIMULATION_TARGET_LEAVE_LEVEL_SIZE 2    
#define SIMULATION_TARGET_LARGE_STATE_SIZE 1    
#define SIMULATION_TARGET_WATER_STATE_SIZE 1    
#define SIMULATION_TARGET_STY_ENTER_FLAG_SIZE 1    
#define SIMULATION_TARGET_STY_POS_INDEX_SIZE 1    
#define SIMULATION_TARGET_STY_COORD_STATE_SIZE 1    
#define SIMULATION_TARGET_X_STYLUS_ANGLE_SIZE 2    
#define SIMULATION_TARGET_Y_STYLUS_ANGLE_SIZE 2    


//  sty_frame
#define STY_FRAME_PROTOCOL             (17000|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus protocol(0:none; 1:usi; 2:gpp1.5; 3:gpp3.0; 4:hpp2.2; 5:hpp3.0; 6:mpp1.5; 7:mpp2.0; 8:lpp; 9:opp)
#define STY_FRAME_STATE                (17001|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus app state(0:none; 1:finger; 2:outrange; 3:hover; 4:tip)
#define STY_FRAME_KEY                  (17002|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus key info
#define STY_FRAME_PRESSURE             (17003|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Stylus pressure
#define STY_FRAME_FREQ_A               (17004|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Frequence A of stylus sample
#define STY_FRAME_FREQ_B               (17005|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Frequence B of stylus sample
#define STY_FRAME_NEXT_FREQ_A          (17006|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Next frequence A of stylus sample
#define STY_FRAME_NEXT_FREQ_B          (17007|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Next frequence B of stylus sample
#define STY_FRAME_NOISE_DATA           (17008|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Array of stylus noise rawdata
#define STY_FRAME_FRAME_VER            (17009|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // version of stylus framedata
#define STY_FRAME_STYLUS_STRUCT_LEN    (17010|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Stylus struct len
#define STY_FRAME_STYLUS_HEAD_LEN      (17011|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus head len
#define STY_FRAME_PACK_HEAD_LEN        (17012|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus pack head len
#define STY_FRAME_STYLUS_PACK_CNT      (17013|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus pack head cnt
#define STY_FRAME_STYLUS_PACK_CTL      (17014|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_HEX)) // Frame control(bit0:PackHeadEn/bit1:highrateEn/bit2-15:res)
#define STY_FRAME_MAX_COL              (17015|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // different stylus protocol max col
#define STY_FRAME_STYMODE_POS          (17016|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // data is only use for stylus mode
#define STY_FRAME_MAX                  17   

#define STY_FRAME_PROTOCOL_SIZE        1    
#define STY_FRAME_STATE_SIZE           1    
#define STY_FRAME_KEY_SIZE             1    
#define STY_FRAME_PRESSURE_SIZE        2    
#define STY_FRAME_FREQ_A_SIZE          2    
#define STY_FRAME_FREQ_B_SIZE          2    
#define STY_FRAME_NEXT_FREQ_A_SIZE     2    
#define STY_FRAME_NEXT_FREQ_B_SIZE     2    
#define STY_FRAME_NOISE_DATA_SIZE      2    
#define STY_FRAME_FRAME_VER_SIZE       1    
#define STY_FRAME_STYLUS_STRUCT_LEN_SIZE 2    
#define STY_FRAME_STYLUS_HEAD_LEN_SIZE 1    
#define STY_FRAME_PACK_HEAD_LEN_SIZE   1    
#define STY_FRAME_STYLUS_PACK_CNT_SIZE 1    
#define STY_FRAME_STYLUS_PACK_CTL_SIZE 1    
#define STY_FRAME_MAX_COL_SIZE         1    
#define STY_FRAME_STYMODE_POS_SIZE     1    


//  sty_packet
#define STY_PACKET_SAMPLE_TIME         (18000|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Stylus packet sample time stamp
#define STY_PACKET_REAL_LEN            (18001|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_DEC)) // Stylus real length
#define STY_PACKET_SAMPLE_SEQUENCE     (18002|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_HEX)) // Stylus sample sequence(bit0-4:StateList; bit5-9:PosIndex; bit10-15:res)
#define STY_PACKET_SAMPLE_TYPE         (18003|MAKE_ATTR(ATTR_WORD|ATTR_UNSIGNED|ATTR_HEX)) // Stylus sample type(bit0-2:SampleDirection; bit3-7:DataType; bit8-9:DspFreqNum; bit10-15:sampleType)
#define STY_PACKET_DATA                (18004|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of stylus data, length=real_len
#define STY_PACKET_LOG                 (18005|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of stylus log,  length=real_len
#define STY_PACKET_TFO                 (18006|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of stylus tfo,  length=real_len
#define STY_PACKET_ATAN                (18007|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of stylus atan,  length=real_len
#define STY_PACKET_POS_INDEX_RUNNING   (18008|MAKE_ATTR(ATTR_BYTE|ATTR_UNSIGNED|ATTR_DEC)) // Stylus position index running
#define STY_PACKET_FINGER_NOR_RAW_DATA (18009|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of finger mode Stylus normal raw data, length=real_len
#define STY_PACKET_FINGER_NOR_IQ_DATA  (18010|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of finger mode Stylus normal iq data, length=real_len
#define STY_PACKET_CONFIRM_NOR_RAW_DATA (18011|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of confirm mode Stylus normal raw data, length=real_len
#define STY_PACKET_CONFIRM_NOR_IQ_DATA (18012|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of confirm mode Stylus normal iq data, length=real_len
#define STY_PACKET_STYLUS_NOR_RAW_DATA (18013|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of stylus mode Stylus normal raw data, length=real_len
#define STY_PACKET_STYLUS_NOR_IQ_DATA  (18014|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of stylus mode Stylus normal iq data, length=real_len
#define STY_PACKET_FINGER_RPT_RAW_DATA (18015|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of finger mode Stylus repeat raw data, length=real_len
#define STY_PACKET_FINGER_RPT_IQ_DATA  (18016|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of finger mode Stylus repeat iq data, length=real_len
#define STY_PACKET_STYLUS_RPT_RAW_DATA (18017|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of stylus mode Stylus repeat raw data, length=real_len
#define STY_PACKET_STYLUS_RPT_IQ_DATA  (18018|MAKE_ATTR(ATTR_WORD|ATTR_SIGNED|ATTR_DEC))  // Array of stylus mode Stylus repeat iq data, length=real_len
#define STY_PACKET_MAX                 19   

#define STY_PACKET_SAMPLE_TIME_SIZE    2    
#define STY_PACKET_REAL_LEN_SIZE       2    
#define STY_PACKET_SAMPLE_SEQUENCE_SIZE 2    
#define STY_PACKET_SAMPLE_TYPE_SIZE    2    
#define STY_PACKET_DATA_SIZE           2    
#define STY_PACKET_LOG_SIZE            2    
#define STY_PACKET_TFO_SIZE            2    
#define STY_PACKET_ATAN_SIZE           2    
#define STY_PACKET_POS_INDEX_RUNNING_SIZE 1    
#define STY_PACKET_FINGER_NOR_RAW_DATA_SIZE 2    
#define STY_PACKET_FINGER_NOR_IQ_DATA_SIZE 2    
#define STY_PACKET_CONFIRM_NOR_RAW_DATA_SIZE 2    
#define STY_PACKET_CONFIRM_NOR_IQ_DATA_SIZE 2    
#define STY_PACKET_STYLUS_NOR_RAW_DATA_SIZE 2    
#define STY_PACKET_STYLUS_NOR_IQ_DATA_SIZE 2    
#define STY_PACKET_FINGER_RPT_RAW_DATA_SIZE 2    
#define STY_PACKET_FINGER_RPT_IQ_DATA_SIZE 2    
#define STY_PACKET_STYLUS_RPT_RAW_DATA_SIZE 2    
#define STY_PACKET_STYLUS_RPT_IQ_DATA_SIZE 2    

#endif //__THP_REPLAY_TYPE_H__
